spring:
  jpa:
    open-in-view: false

  flyway:
    enabled: true
    validate-migration-naming: true

binance:
  api:
    key: ${BINANCE_API_KEY:}
    secret: ${BINANCE_API_SECRET:}

trading:
  symbols:
    - ETHUSDT
    - BTCUSDT

  safety:
    dedicated-account: ${TRADING_DEDICATED_ACCOUNT:false}